project:
  type: book

book:
  title: Quantifying Pressing Effectiveness and Its Impact on Formations in Football
  author: Kenneth Ssekimpi
  chapters:
    - index.qmd
    - chapters/chapter-00/_introduction.qmd
    # - summary.qmd
    - backmatter/bibliography/_references.qmd
  
metadata:
  student_number: SSKKEN001
  degree: Master in Philosophy in Data Science
  course: STA5093W - Data Science Minor Dissertation
  university: University of Cape Town
  faculty: Faculty of Science
  department: Department of Statistical Sciences
  year: 2025
  supervisor: Mr Neil Watson
  supervisor_title: Lecturer, Department of Statistical Sciences, University of Cape Town
  supervisor_email: nm.watson@uct.ac.za
  wordcount: 15000
  keywords: [Football Analytics, Pressing, VPEP, Machine Learning, Defensive Metrics]
  bibliography: backmatter/bibliography/references.bib
  csl: harvard-university-of-cape-town.csl
  citeproc: true
  appendix-cite-as: display
  google-scholar: true
  nocite: "@*"
  crossref:
    chapters: true
  toc: true
  number-sections: true
  top-level-division: chapter


format:
  pdf:
    documentclass: uct-thesis-template
    classoption: [twoside]
    papersize: a4
    # geometry: hmargin={3.6cm, 2.6cm}, vmargin={2.5cm, 2.7cm}
    template-partials:
      - frontmatter/title.tex
      - frontmatter/before-body.tex
      - frontmatter/toc.tex
    include-in-header: 
      - frontmatter/header.tex
    keep-tex: true
    output-file: ssekimpi-mphil2025.pdf
    
  html:
    theme: cosmo
    toc: true

editor: visual

