# Introduction

## Background

Association football, also known as soccer, is a game played by two teams of 11 players each. Teams compete by advancing a ball into their opponent's goal, adhering to established rules that govern gameplay, player conduct, and scoring, with the aim to score more goals than their rivals [@memmert_data_2018; @sumpter_soccermatics_2016]. Although the fundamental simplicity of football contributes significantly to its global popularity and appeal, the game simultaneously possesses incredible complexity characterised by movement patterns, match plans, playing philosophies, and creativity [@bornn_soccer_2018; @vicente_why_2024]. These qualities are collectively referred to as football tactics [@memmert_data_2018].

Football tactics involve strategically positioning players on the field and co-ordinating their movements to maximise the chances of winning matches. This encompasses both the formation that a team adopts (that is, the spatial arrangement of players on the pitch) and their overall style of play [@wilson_inverting_2010]. Furthermore, @rein_big_2016 describe football tactics as the actions and strategies implemented by a team and its players during a match to achieve specific goals, primarily winning the game. These actions are typically adaptations to dynamically-changing situations in the match and the behaviour of the opposing team, managing space, time, and individual actions on the pitch.

Fundamental to understanding these tactical deployments are the distinct player positions and the common tactical formations they operate within. Football teams are typically composed of players in four main categories: Goalkeepers (GK), primarily responsible for preventing goals; Defenders (DEF), who protect their goal and prevent opposing attacks (e.g., Centre-Backs, Full-Backs); Midfielders (MID), who link defence and attack and control central areas (e.g., Defensive Midfielders, Attacking Midfielders, Wingers); and Forwards/Strikers (FWD), whose main role is to score goals. These positions are strategically arranged into tactical formations, which dictate a team's general shape and approach during different phases of play. A phase of play in football refers to a segment of a match, typically defined for analysis or coaching purposes, characterised by the actions and organisation of one or both teams [@ghezzi2024]. It can be understood as a sequence of consecutive events or actions that fit together [@decroos_soccer_2020]
